import Foundation

/// Uma entrada do histórico da área de transferência.
public struct ItemCopiado: Identifiable, Codable, Equatable, Sendable {
    public enum Tipo: String, Codable, Sendable {
        case texto, link, arquivos
    }

    public var id: UUID
    public var tipo: Tipo
    /// O texto, o endereço, ou os caminhos separados por quebra de linha.
    public var valor: String
    public var copiadoEm: Date
    /// Fixado não sai pelo limite nem pelo "apagar histórico".
    public var fixado: Bool

    public init(id: UUID = UUID(), tipo: Tipo, valor: String,
                copiadoEm: Date = Date(), fixado: Bool = false) {
        self.id = id
        self.tipo = tipo
        self.valor = valor
        self.copiadoEm = copiadoEm
        self.fixado = fixado
    }

    public var caminhos: [String] {
        tipo == .arquivos ? valor.components(separatedBy: "\n") : []
    }

    /// Uma linha para a lista: espaços e quebras viram um espaço só.
    public var resumo: String {
        switch tipo {
        case .arquivos:
            let nomes = caminhos.map { ($0 as NSString).lastPathComponent }
            return nomes.count == 1 ? nomes[0] : "\(nomes.count) arquivos — \(nomes.joined(separator: ", "))"
        case .texto, .link:
            let uma = valor.split(whereSeparator: { $0.isWhitespace || $0.isNewline }).joined(separator: " ")
            return HistoricoDeCopias.encurtar(uma, ate: 120)
        }
    }
}

public enum HistoricoDeCopias {

    public static let limitePadrao = 100
    public static let maximoDeCaracteres = 50_000

    /// Marcas que os apps põem no que NÃO deve ir para um histórico — a
    /// convenção de nspasteboard.org, seguida por gerenciadores de senha.
    /// Senha copiada não pode ficar guardada num arquivo do Docka.
    public static let tiposSigilosos: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    public static func deveIgnorar(tipos: [String]) -> Bool {
        tipos.contains(where: tiposSigilosos.contains)
    }

    /// Texto copiado vira item: só um endereço web é link; o resto é texto.
    public static func item(deTexto texto: String, em data: Date = Date()) -> ItemCopiado? {
        let limpo = texto.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !limpo.isEmpty else { return nil }
        if !limpo.contains(where: \.isWhitespace),
           let url = URL(string: limpo),
           ["http", "https"].contains(url.scheme?.lowercased() ?? ""),
           url.host != nil {
            return ItemCopiado(tipo: .link, valor: limpo, copiadoEm: data)
        }
        // o original, com os espaços dele: é o que vai voltar ao colar
        return ItemCopiado(tipo: .texto, valor: String(texto.prefix(maximoDeCaracteres)), copiadoEm: data)
    }

    /// Põe o novo no topo. Copiar de novo o que já está lá só o traz para
    /// cima (mantendo se estava fixado); o limite descarta os mais antigos
    /// que não estão fixados.
    public static func registrar(_ novo: ItemCopiado, em itens: [ItemCopiado],
                                 limite: Int = limitePadrao) -> [ItemCopiado] {
        var r = itens
        var entrada = novo
        if let i = r.firstIndex(where: { $0.tipo == novo.tipo && $0.valor == novo.valor }) {
            entrada.fixado = r[i].fixado
            entrada.id = r[i].id
            r.remove(at: i)
        }
        r.insert(entrada, at: 0)
        var soltos = 0
        return r.filter { item in
            if item.fixado { return true }
            soltos += 1
            return soltos <= limite
        }
    }

    /// Busca sem diferenciar maiúscula nem acento: "acao" acha "Ação".
    public static func buscar(_ termo: String, em itens: [ItemCopiado]) -> [ItemCopiado] {
        let t = termo.trimmingCharacters(in: .whitespaces)
        guard !t.isEmpty else { return itens }
        return itens.filter {
            $0.valor.range(of: t, options: [.caseInsensitive, .diacriticInsensitive]) != nil
        }
    }

    /// Fixados primeiro, cada grupo do mais recente para o mais antigo — é a
    /// ordem da lista.
    public static func ordenados(_ itens: [ItemCopiado]) -> [ItemCopiado] {
        itens.filter(\.fixado) + itens.filter { !$0.fixado }
    }

    public static func encurtar(_ s: String, ate n: Int) -> String {
        s.count <= n ? s : String(s.prefix(n - 1)) + "…"
    }
}

/// Limpa parâmetros de rastreamento de um link.
public enum LimparLink {

    /// Parâmetros que só servem para rastrear quem clicou de onde.
    static let rastreadores: Set<String> = [
        "fbclid", "gclid", "gbraid", "wbraid", "dclid", "msclkid", "yclid",
        "twclid", "ttclid", "igshid", "igsh", "mc_cid", "mc_eid", "_hsenc",
        "_hsmi", "mkt_tok", "vero_id", "oly_anon_id", "oly_enc_id",
        "rb_clickid", "s_cid", "_ga", "_gl", "ref_src", "ref_url",
    ]

    /// `si` é rastreador no YouTube e no Spotify, mas em outros sites pode
    /// ser parte do endereço — só sai nesses dois.
    static let rastreadoresPorSite: [String: Set<String>] = [
        "youtube.com": ["si", "feature", "pp"],
        "youtu.be": ["si", "feature"],
        "spotify.com": ["si", "context"],
        "amazon.com": ["ref", "ref_", "pf_rd_r", "pf_rd_p", "pd_rd_r", "pd_rd_w", "pd_rd_wg"],
        "amazon.com.br": ["ref", "ref_", "pf_rd_r", "pf_rd_p", "pd_rd_r", "pd_rd_w", "pd_rd_wg"],
    ]

    /// O link sem os rastreadores, ou `nil` se não havia nada a tirar (ou não
    /// é um link web).
    public static func limpar(_ texto: String) -> String? {
        let t = texto.trimmingCharacters(in: .whitespacesAndNewlines)
        guard var c = URLComponents(string: t),
              ["http", "https"].contains(c.scheme?.lowercased() ?? ""),
              let host = c.host?.lowercased(),
              let itens = c.queryItems, !itens.isEmpty else { return nil }
        let doSite = rastreadoresPorSite.first { host == $0.key || host.hasSuffix("." + $0.key) }?.value ?? []
        let restantes = itens.filter { item in
            let n = item.name.lowercased()
            return !(n.hasPrefix("utm_") || rastreadores.contains(n) || doSite.contains(n))
        }
        guard restantes.count != itens.count else { return nil }
        c.queryItems = restantes.isEmpty ? nil : restantes
        return c.string
    }
}

/// Depois de quanto tempo a área de transferência se apaga sozinha.
public enum ApagarClipboard: Int, CaseIterable, Identifiable, Sendable {
    case nunca = 0
    case umMinuto = 60
    case cincoMinutos = 300
    case quinzeMinutos = 900
    case umaHora = 3600

    public var id: Int { rawValue }

    public var titulo: String {
        switch self {
        case .nunca:         return "Nunca"
        case .umMinuto:      return "Depois de 1 minuto"
        case .cincoMinutos:  return "Depois de 5 minutos"
        case .quinzeMinutos: return "Depois de 15 minutos"
        case .umaHora:       return "Depois de 1 hora"
        }
    }

    public init(persisted: Int) { self = ApagarClipboard(rawValue: persisted) ?? .nunca }
}
